#!/bin/bash
# CloudFlare Tunnelを使ってHTTPS対応

echo "=========================================="
echo "CloudFlare Tunnel セットアップ"
echo "=========================================="
echo ""
echo "CloudFlare Tunnelを使えば、ドメイン名なしで"
echo "HTTPS対応できます（完全無料）"
echo ""
echo "【手順】"
echo ""
echo "1. CloudFlareアカウントを作成（無料）"
echo "   https://dash.cloudflare.com/sign-up"
echo ""
echo "2. cloudflaredをインストール"
echo "   brew install cloudflare/cloudflare/cloudflared"
echo ""
echo "3. CloudFlareにログイン"
echo "   cloudflared tunnel login"
echo ""
echo "4. トンネルを作成"
echo "   cloudflared tunnel create estat-mcp"
echo ""
echo "5. トンネルを設定"
echo "   cat > ~/.cloudflared/config.yml << 'EOF'"
echo "tunnel: <TUNNEL_ID>"
echo "credentials-file: /Users/$(whoami)/.cloudflared/<TUNNEL_ID>.json"
echo ""
echo "ingress:"
echo "  - hostname: estat-mcp.your-domain.com"
echo "    service: http://estat-mcp-alb-633149734.ap-northeast-1.elb.amazonaws.com"
echo "  - service: http_status:404"
echo "EOF"
echo ""
echo "6. DNSレコードを追加"
echo "   cloudflared tunnel route dns estat-mcp estat-mcp.your-domain.com"
echo ""
echo "7. トンネルを起動"
echo "   cloudflared tunnel run estat-mcp"
echo ""
echo "8. Kiro設定を更新"
echo "   url: https://estat-mcp.your-domain.com"
echo ""
echo "詳細: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/"
echo ""
